[build]
target = "wasm32-wasip1"
rustflags = [
    # The auto splitting runtime supports all the following WASM features.
    "-C", "target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+sign-ext,+simd128,+relaxed-simd",
]