[package]
name = "baldis_basics_classic_remastered"
version = "0.1.0"
edition = "2021"

[dependencies]
asr = { workspace = true, features = ["alloc", "derive", "unity"] }
bytemuck = "1.23.1"
helpers = { path = "../helpers", features = ["unity"] }
once_cell = "1.19.0"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = { version = "0.28.0", features = [] }

[lib]
crate-type = ["cdylib"]
