name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rust-src
          rust-version: stable
          targets: wasm32-unknown-unknown

      - name: Build
        run: |
          cargo b --release --locked

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/wasm32-unknown-unknown/release/dismantled.wasm
            target/wasm32-unknown-unknown/release/selaco.wasm
            target/wasm32-unknown-unknown/release/snap_the_sentinel.wasm
          name: ${{ steps.vars.outputs.sha_short }}
          tag_name: ${{ steps.vars.outputs.sha_short }}
          body: |
            This is the release version of the autosplitters in this repo at ${{ github.sha }}.
            
            You can access the latest version of all the autosplitters at `https://github.com/mitchell-merry/livesplit-zdoom/releases/download/latest/<name>.wasm`
            
            For example, you will always find the latest version of Dismantled's autosplitter at:
            https://github.com/mitchell-merry/livesplit-zdoom/releases/download/latest/dismantled.wasm.

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
          targets: 'wasm32-unknown-unknown'

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
