name: Release

on:
  workflow_dispatch:
    inputs:
      autosplitter:
        description: 'The autosplitter to release.'
        required: true
        type: choice
        options:
          - dismantled
          - doom_the_dark_ages
          - kuru_kuru_kururin
          - selaco
          - snap_the_sentinel

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set outputs
        id: vars
        run: echo "version=v$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rust-src
          rust-version: stable
          targets: wasm32-wasip1

      - name: Build
        run: |
          cargo b --release --locked --package ${{ inputs.autosplitter }}

      - name: Release autosplitter at unique tag
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/wasm32-wasip1/release/${{ inputs.autosplitter }}.wasm
          name: ${{ inputs.autosplitter }}@${{ steps.vars.outputs.version }}
          tag_name: ${{ inputs.autosplitter }}-${{ steps.vars.outputs.version }}
          body: |
            This is the release version of the ${{ inputs.autosplitter }} autosplitter at ${{ github.sha }}.
            
            You can access this version of the autosplitter at:
            https://github.com/mitchell-merry/autosplitters-wasm/releases/download/${{ inputs.autosplitter }}-${{ steps.vars.outputs.version }}/${{ inputs.autosplitter }}.wasm
            
            or you can find the latest at:
            https://github.com/mitchell-merry/autosplitters-wasm/releases/download/${{ inputs.autosplitter }}-latest/${{ inputs.autosplitter }}.wasm

      - name: Release autosplitter at latest tag
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/wasm32-wasip1/release/${{ inputs.autosplitter }}.wasm
          name: ${{ inputs.autosplitter }}
          tag_name: ${{ inputs.autosplitter }}-latest
          body: |
            This is the latest release version of the ${{ inputs.autosplitter }} autosplitter.
            
            You can access the latest version of the autosplitter at:
            https://github.com/mitchell-merry/autosplitters-wasm/releases/download/${{ inputs.autosplitter }}-latest/${{ inputs.autosplitter }}.wasm
