name: Release

on:
  workflow_dispatch:
    inputs:
      autosplitter:
        description: 'The autosplitter to release.'
        required: true
        type: choice
        options:
          - dismantled
          - doom_the_dark_ages
          - kuru_kuru_kururin
          - selaco
          - snap_the_sentinel

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{ inputs.autosplitter }}
    steps:
      - name: Print the chosen autosplitter to STDOUT
        run: echo  The autosplitter is ${{ inputs.autosplitter }}

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set outputs
        id: vars
        run: echo "version=v$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rust-src
          rust-version: stable
          targets: wasm32-wasip1

      - name: Build
        run: |
          cargo b --release --locked

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/wasm32-wasip1/release/*.wasm
          name: ${{ steps.vars.outputs.version }}
          tag_name: ${{ steps.vars.outputs.version }}
          body: |
            This is the release version of the autosplitters in this repo at ${{ github.sha }}.
            
            You can access the latest version of all the autosplitters at `https://github.com/mitchell-merry/autosplitters-wasm/releases/download/latest/<name>.wasm`
            
            For example, you will always find the latest version of Dismantled's autosplitter at:
            https://github.com/mitchell-merry/autosplitters-wasm/releases/download/latest/dismantled.wasm.
